name: stats_probability_utils
description: >-
  Calculate measures of central tendency, position and dispersion for grouped and ungrouped data.
version: 0.9.0
homepage: https://github.com/valdezmanuel/stats_probability_utils

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.9.0